name: foursquare_pilgrimsdk
description: Pilgrim SDK for Flutter.
version: 0.0.1
author: Matthew Huie <matthew@matthewhuie.com>
homepage: matthewhuie.com

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.matthewhuie.flutter.foursquare.pilgrimsdk
    pluginClass: FoursquarePilgrimSdkPlugin